dist: xenial
addons:
  apt:
    sources:
      - mysql-5.7-xenial
    packages:
      - mysql-server
      - mysql-client
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
services:
  - mongodb
  - mysql
language: node_js
node_js:
  - "lts/*"
  - "node"
cache:
  directories:
    - node_modules
before_install:
  - npm config set spin false
  - mysql -u root -e "CREATE DATABASE IF NOT EXISTS test_vault_orm;"
  - mysql -u travis -e "show plugins"
  - mysql -u root -e "INSTALL PLUGIN mysqlx SONAME 'mysqlx.so'"
  - mysqlsh -u root -h localhost --classic --dba enableXProtocol
  - mysql -u root -e "GRANT ALL PRIVILEGES ON test_vault_orm.* TO 'travis'@'localhost';";
  - mysql -u root -e "show plugins"
  - mysql -u travis -e "show plugins"
  - npm install -g codeclimate-test-reporter
install:
  - npm i .
script:
  - npm run cover
  - codeclimate-test-reporter < coverage/lcov.info
after_success:
  - npx tsc --sourceMap false
  - npx semantic-release
